hw: tests for petstore API done
yuliiaKyhym/petstore pull request #1
Opened 2023-03-01 17:09 UTC by yuliiaKyhym

2023-03-01 19:41 UTC, SanitarskyiDmytro requested changes

2023-03-01 19:41 UTC, SanitarskyiDmytro commented on cypress/e2e/petTest.cy.js
> +    body: {
Хардкод потрібно видалити і зробити через фікстуру як в усіх тестах)

2023-03-02 11:01 UTC, yuliiaKyhym commented on cypress/e2e/petTest.cy.js
> +    body: {
fixed

2023-03-02 13:50 UTC, SanitarskyiDmytro requested changes

2023-03-02 13:50 UTC, SanitarskyiDmytro commented on cypress/e2e/petTest.cy.js
> +    body: {
Я мав на увазі весь обʼєкт)

Ось цей:
```
{
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "doggie",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}
```

замінити на змінну)

Щоб запит з такого:

```
cy.request({
    method: 'PUT',
    url: '/pet',
    body: {
      "id": pet.id,
      "category": {
        "id": updatedCategoryId,
        "name": updatedCategoryName
      },
      "name": UpdatedPetName,
      "photoUrls": [
        pet.photoUrls
      ],
      "tags": [
        {
          "id": pet.tags.id,
          "name": pet.tags.name,
        }
      ],
      "status": pet.status
    }
    })
```
    
    Став таким:
    
```
    cy.request({
    method: 'PUT',
    url: '/pet',
    body: pet
    })
    
```

2023-03-02 13:50 UTC, SanitarskyiDmytro commented on cypress/e2e/petTest.cy.js
> +    body: {
по всім запитам така проблема)

2023-03-02 15:27 UTC, SanitarskyiDmytro approved these changes

2023-03-02 17:01 UTC, merged